//Автоматически генерируемые идентификаторы ресурсов

#define IMG_TILE_SNOW	0
#define IMG_BACK_SNOW	1
#define IMG_SUN	2
#define IMG_TILE_LAB	3
#define IMG_BACK_LAB	4
#define IMG_WIN	5
#define IMG_DEATH	6
#define IMG_VIRUS	7
#define IMG_MINE	8
#define IMG_SNOWMOB	9
#define IMG_BACK_MENU	10
#define IMG_TILE_MINE	11
#define IMG_BACK_MINE	12
#define IMG_TILE_HUD	13
#define IMG_IMG_HUD	14
#define IMG_FONT	15
#define IMG_CHAPTER_1	16
#define IMG_CHAPTER_2	17
#define IMG_CHAPTER_3	18

#define PAL_TILE_SNOW	0
#define PAL_TILE_MINE	1
#define PAL_TILE_LAB	2
#define PAL_SUN	3

#define MUS_MENU	0
#define MUS_LEVEL1	1
#define MUS_LEVEL2	2
#define MUS_LEVEL3	3


#define SPR_PLAYER	0
#define SPR_SHOT	32
#define SPR_LIGHT_1_MINE	39
#define SPR_LIGHT_2_MINE	51
#define SPR_MINE_JUMP	63
#define SPR_ANGRY_PLANT_R	83
#define SPR_ANGRY_PLANT_L	103
#define SPR_ANGRY_PLANT	123
#define SPR_COAL	143
#define SPR_BAT	163
#define SPR_SPIDER	175
#define SPR_ZOMBI	195
#define SPR_B_SLIME	215
#define SPR_COLBA	227
#define SPR_S_SLIME_LAB	247
#define SPR_LIGHT_1_LAB	259
#define SPR_LIGHT_2_LAB	271
#define SPR_FAN	283
#define SPR_ACID	291
#define SPR_ZOMBI_HAT	331
#define SPR_LIGHT_1_SNOW	351
#define SPR_LIGHT_2_SNOW	363
#define SPR_WATER_MINE	375
#define SPR_S_SLIME	415
#define SPR_OWL	427
#define SPR_STALACT	439
#define SPR_ICE_SPIKE	459
#define SPR_BLOCK	479
#define SPR_SNOW_JUMP	499
#define SPR_WATER_SNOW	519

#define SFX_SHOT	0
#define SFX_BOOM	1
#define SFX_HEALTH	2
#define SFX_HEALTH_FULL	3
#define SFX_LOAD	4
#define SFX_LOAD_FULL	5
#define SFX_DAMAGE	6
#define SFX_DEATH	7
#define SFX_JUMP_UP	8
#define SFX_JUMP_DOWN	9
#define SFX_STEP	10
#define SFX_STALACTIT	11
#define SFX_ENEMY_DEATH	12
#define SFX_STEP_STAIRS	13
#define SFX_MENU	14
